#!/bin/bash
#copyright 2012, 2015 Wu, Xingbo <wuxb45@gmail.com>
#pullall: pull from git/hg/svn repositories.

blacklist=$(cat pullall.blacklist 2>/dev/null)
WD=$(pwd)

# no match -> 0, match -> 1
bcheck ()
{
  if [[ -z "$blacklist" ]]; then
    return 0
  fi
  for black in $blacklist;
  do
    if [[ $black == $1 ]]; then
      return 1
    fi
  done
  return 0
}

# $1: dirname
pulldir ()
{
  local dir="${1}"
  bcheck "${dir}"
  if [[ $? -eq 0 ]]; then
    echo "#### Updating [${dir}]"
    if [[ -d "${dir}/.git" ]]; then
      cd "${dir}" && git pull
      cd ${WD}
    elif [[ -d "${dir}/.svn" ]]; then
      cd "${dir}" && svn update
      cd ${WD}
    elif [[ -d "${dir}/.hg" ]]; then
      cd "${dir}" && hg pull && hg update
      cd ${WD}
    else
      echo "#### Ignoring ${dir}"
    fi
  else
    echo "#### Skipping ${dir} (blacklist)"
  fi
}

(
  flock -n 9 || exit 1
  ping -q -c 4 8.8.8.8 &>/dev/null
  if [[ $? -ne 0 ]]; then
    echo "network failed, abort."
    exit 0
  fi

  echo "start   @ $(date)" | tee -a pullall.history
  for repo in $(ls 2>/dev/null);
  do
    pulldir "${repo}"
  done
  echo "finished@ $(date)" | tee -a pullall.history

) 9>/tmp/pullall.lock

